config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'sign_in', to: 'sessions#new'

  resources :sessions, only: [:new, :create]
  delete 'sign_out', to: 'sessions#destroy'

  resources :steps, only: [:index, :edit, :update] do
    put :update_project_variable, on: :member
    get :manifest, on: :member, defaults: { format: :xml }
    post :result, on: :member, defaults: { format: :json }
    put :sync_with_project_variable, on: :member
  end

  resources :period_ratings

  resources :project_variables, only: [:index]

  resources :accounts, only: [:index]

  namespace :admin do
    resources :steps, only: [:index, :edit, :update] do
      resources :step_permissions
    end
  end

end

app/models/step.rb
class Step < ActiveRecord::Base
	validates :name, :display_name, :url, presence: true
	validates :name, uniqueness: true
	validates_format_of :url, with: URI.regexp

	has_many :variables, class_name: StepVariable, dependent: :destroy
  has_many :step_permissions, dependent: :destroy

	accepts_nested_attributes_for :variables

  before_destroy :clear_ratings

	DETECT_MOBILE_OPERATOR = 'detect_mobile_operator'
  DATE = 'date'
	PERIOD_RATING = 'period_rating'
  STORE_PERIOD_RATING = 'store_period_rating'
  NEW_CALLER = 'new_caller'

  def self.type(name)
    step_name = name.camelize
    "Steps::#{step_name}".constantize
  end

  def clear_ratings
    PeriodRating.destroy_all(step_id: id)
  end

end

app/models/steps/back_end.rb
module Steps
  class BackEnd
    def self.authenticate_account!
      @@authentication = Service::Authentication.new(ENV['EMAIL'], ENV['SECRET'])
      account = @@authentication.login!

      if(@@authentication.success?)
        ActiveApi.init_auth(account)
      end
    end

    def self.authenticated?
      @@authentication.success?
    end
  end
end

app/models/steps/date.rb
module Steps
  class Date
    def self.response options={}
      number_of_days = DateUnit.new(options[:unit].downcase, options[:value].to_i).days
      date = number_of_days.days.ago.strftime("%d/%m/%Y") if number_of_days
      "{\"result\": \"#{date}\"}"
    end
  end
end

app/models/steps/detect_mobile_operator.rb
module Steps
  class DetectMobileOperator
    def self.response options={}
      tel = Tel.new(options[:address])
      "{\"result\": \"#{tel.operator.code}\"}"
    end
  end
end

app/models/steps/new_caller.rb
module Steps
  class NewCaller
    def self.response options={}
      channel_id = options[:channel_id]
      address = options[:address]

      begin
        BackEnd.authenticate_account!
        is_exist = ::CallLog.exist?(channel_id, address) ? 0 : 1
      rescue Service::ApiException => e
        is_exist = 'unauthorized'
      end

      "{\"result\": \"#{is_exist}\"}"
    end
  end
end

app/models/steps/period_rating.rb
module Steps
  class PeriodRating
    def self.response options={}
      tel = Tel.new(options[:address])
      now = ::Date.today
      
      code = ::PeriodRating.get_code_of now, tel

      "{\"result\": \"#{code}\"}"
    end
  end
end

app/models/steps/store_period_rating.rb
module Steps
  class StorePeriodRating
    def self.response options={}
      tel = Tel.new(options[:address])
      now = ::Date.today
      rating = ::PeriodRating.get(now)

      is_registered = 0
      if rating
        rating.register! tel
        is_registered = rating.has_telephone?(tel) ? 1 : 0
      end
            
      "{\"result\": \"#{is_registered}\"}"
    end
  end
end

app/controllers/admin/steps_controller.rb
class Admin::StepsController < AdminController

  def index
    @steps = Step.all
  end

  private

  def protected_project_params
    params.require(:step).permit(:project_id)
  end

end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:manifest, :result]
  skip_before_action :verify_authenticity_token, only: [:manifest, :result]

  add_breadcrumb 'Steps', :steps_path

  def index
    @steps = current_access.steps
  end

  def edit
    @ratings = PeriodRating.all if params[:id] == Step::PERIOD_RATING
    @operators = Operator.all if params[:id] == Step::DETECT_MOBILE_OPERATOR
    @step = Step.find_by_name(params[:id])

    append_breadcrumbs
  end

  def update
    if params[:id] == Step::DETECT_MOBILE_OPERATOR
      Operator.update_prefix_setting params[:operators]
    end

    redirect_to steps_path, notice: "Step #{params[:id]} has been updated"
  end

  def update_project_variable
    is_valid = false
    step = Step.find_by_name(params[:id])

    if params[:step][:project_id].present? && params[:step][:variable_id].present?
      if step.update_attributes(protected_project_params)
        is_valid = true
      end
    end

    if is_valid
      redirect_to edit_step_path(step.name), notice: "Step #{params[:id]} has been updated"
    else
      redirect_to edit_step_path(step.name), alert: 'Project and variable is required'
    end
  end

  def sync_with_project_variable
    step = Step.find_by_name(params[:id])
    period_rating = PeriodRating.find(protected_sync_params)
    if step.project_id && step.variable_id
      period_rating.sync_numbers_with! step.project_id, step.variable_id
      redirect_to edit_step_path(step.name), notice: "Rating's numbers has been synchronized"
    else
      redirect_to edit_step_path(step.name), alert: "Please update project and variable before synchronize"
    end
  end

  def manifest
    @step = Step.find_by_name(params[:id])
  end

  def result
    render json: Step.type(params[:id]).response(params)
  end

  private

  def protected_project_params
    params.require(:step).permit(:project_id, :variable_id)
  end

  def protected_sync_params
    params.require(:period_rating_id)
  end

  def append_breadcrumbs
    add_breadcrumb @step.display_name
  end

end

app/views/steps/_operator_codes.html.erb
<div class='mobile-operator-code'>
	<table class="table table-bordered w500">
		<caption><strong>Mobile Operator Code</strong></caption>
	  <thead>
	  	<tr>
	  		<th>Operator Name</th>
	  		<th>Operator Code</th>
  			<th>Prefix</th>
	  	</tr>
	  </thead>
	  <tbody>
	  	<% Operator.all.each do |operator| %>
	  		<tr>
		  		<td class='col-sm-3'><%= operator.name %></td>
		  		<td class='col-sm-3'><%= operator.code %></td>
	  			<td><%= operator.prefixes.join(Operator::SEPERATOR_DISPLAY) %></td>
		  	</tr>
	  	<% end %>
	  </tbody>
	</table>
</div>

<%= render 'prefix_form', step: step %>

app/views/steps/_prefix_form.html.erb
<div class="collapse-group prefix-setting w500">
	<a class="btn btn-collapse" href="#prefix-setting">Prefix Setting »</a>
	<div id='prefix-setting' class="panel collapse">
		<div class="panel-body">
			<%= form_tag("/steps/#{step['name']}", class: 'form', method: :put) do %>

		  	<% Operator.all.each do |operator| %>
		  		<% unless operator.name == 'other' %>
					  <div class="form-group">
					  	<%= label_tag "operators[#{operator.name}]", operator.name, class: 'col-sm-2 control-label' %>
					    <div class="col-sm-10">
					      <%= text_field_tag "operators[#{operator.name}]", operator.prefixes.join(Operator::SEPERATOR), placeholder: operator.name, class: 'form-control prefix-number' %>
					    </div>
					  </div>
				  <% end %>
			  <% end %>

			  <div class="col-sm-2"></div>
			  <div class="form-group col-sm-10">
		      <%= submit_tag "Save", class: 'btn btn-primary' %>
		    </div>

			<% end %>
	  </div>
	</div>
</div>

app/views/steps/_project_settings.html.erb
<div class='project clearfix'>
    <div class='project_variable_form <%= step.project_id.nil? ? '' : 'hide' %> clearfix'>
      <%= form_tag(update_project_variable_step_path(step.name), method: :put) do %>
        <div class='l-side'><strong class='caption'>Project:</strong></div>
        <div class="col-sm-3">
          <%= select_tag "step[project_id]", options_for_select(Service::Project.collection, step.project_id), prompt: '--- select project ---', class: ' form-control' %>
        </div>
        <div class='col-sm-1'><strong class='caption'>Variable:</strong></div>
        <div class='col-sm-3'>
          <%= select_tag 'step[variable_id]', options_for_select(Service::ProjectVariable.collection(step.project_id), step.variable_id), prompt: '--- select variable ---', class: ' form-control' %>
        </div>

        <div class='col-sm-1'>
          <%= submit_tag "Save", id: 'project_variable_submit', class: 'btn btn-primary btn-sm' %>
        </div>
      <% end %>
    </div>

    <div class='project_variable_view <%= step.project_id.nil? ? 'hide' : '' %> clearfix'>
        <div class='l-side'><strong class='caption'>Project:</strong></div>
        <div class="col-sm-2">
          <%= Service::Project.fetch(step.project_id).try(:name) %>
        </div>
        <div class='col-sm-1'><strong class='caption'>Variable:</strong></div>
        <div class='col-sm-2'>
          <%= ProjectVariable.get(step.project_id, step.variable_id).try(:name) %>
        </div>

        <div class='col-sm-1'>
          <%= button_tag "Edit", id: 'project_variable_button', class: 'btn btn-primary btn-xs' %>
        </div>
    </div>

</div>

app/views/steps/_step.xml.erb
<steps>
  <step name="<%=step.name%>"
            display-name="<%= step.display_name %>"
            icon="<%= step.icon %>"
            type="<%= step.kind %>"
            callback-url="http://{service_domain}<%=result_step_path(format: :json) %>">
    <% unless step.variables.incoming.empty? %>
      <settings>
        <% step.variables.incoming.each do |variable| %>
          <variable name="<%= variable.name %>"
                    display-name="<%= variable.display_name %>"
                    type="<%= variable.kind %>"
                    required="true" />
        <% end %>
      </settings>
    <% end %>

    <response type="variables">
      <% step.variables.outgoing.each do |variable| %>
        <variable name="<%= variable.name %>"
                  display-name="<%= variable.display_name %>"
                  type="<%= variable.kind %>" />
      <% end %>
    </response>
  </step>
</steps>

app/views/steps/_table.html.erb
<% unless variables.empty? %>
  <div class='table <%= title %>'>
    <table class="table table-bordered">
      <caption><strong><%= title.camelize %></strong></caption>
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Type</th>
        </tr>
      </thead>
      <tbody>
        <% variables.each do |variable| %>
          <tr>
            <td><%= variable.display_name %></td>
            <td><%= variable.description.html_safe %></td>
            <td><%= variable.kind %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/steps/edit.html.erb
<div class='title'>
	<h3><%= @step.display_name %></h3>
</div>

<div class='description'>
	<p><%= @step.description %></p>
</div>

<div class='manifest'>
  <strong class='caption'>Url manifest:</strong>
  <%= link_to @step.url, @step.url %>
</div>

<br />

<%= render 'table', title: 'inputs', variables: @step.variables.incoming %>
<%= render 'table', title: 'outputs', variables: @step.variables.outgoing %>

<% if params[:id] == Step::DETECT_MOBILE_OPERATOR %>
	<%= render 'operator_codes', step: @step %>
<% elsif params[:id] == Step::PERIOD_RATING %>
	<%= render 'steps/period_ratings/list', step: @step %>
<% end %>

app/views/steps/index.html.erb
<table class="table table-hover">
	<caption><strong>Step List</strong></caption>
	<thead>
		<tr>
			<th class='col-sm-2'>Name</th>
			<th>Description</th>
		</tr>
	</thead>
	<tbody>
		<% @steps.each do |step| %>
			<tr>
				<td><%= link_to step.display_name, edit_step_path(step.name) %></td>
				<td><%= step.description %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/steps/manifest.xml.erb
<?xml version="1.0" encoding="UTF-8" ?>
<verboice-service>
  <name><%= @step.display_name %></name>
  <global-settings>
    <variable name="service_domain" display-name="Service Domain" type="string"/>
  </global-settings>
	
	<%= render 'step', step: @step %>

</verboice-service>