config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'sign_in', to: 'sessions#new'

  resources :sessions, only: [:new, :create]
  delete 'sign_out', to: 'sessions#destroy'

  resources :steps, only: [:index, :edit, :update] do
    put :update_project_variable, on: :member
    get :manifest, on: :member, defaults: { format: :xml }
    post :result, on: :member, defaults: { format: :json }
    put :sync_with_project_variable, on: :member
  end

  resources :period_ratings

  resources :project_variables, only: [:index]

  resources :accounts, only: [:index]

  namespace :admin do
    resources :steps, only: [:index, :edit, :update] do
      resources :step_permissions
    end
  end

end

app/models/step_permission.rb
class StepPermission < ActiveRecord::Base
  belongs_to :step
  validates :user_id, presence:true, uniqueness: { scope: :step }
  validates :user_email, presence: true, uniqueness: { scope: :step }
end

app/controllers/admin/step_permissions_controller.rb
class Admin::StepPermissionsController < AdminController
  
  def index
    @step = Step.find(params[:step_id])
    @step_permissions = @step.step_permissions.order('created_at DESC').page(params[:page])
  end

  def create
     @step = Step.find(params[:step_id])
     @step_permission = @step.step_permissions.build(filter_params)

     if @step_permission.save
       render layout: false
     else
       render text: @step_permission.errors.full_messages.first, status: 403
     end
  end

  def destroy
    @step_permission = Step.find(params[:step_id]).step_permissions.find(params[:id])
    if(@step_permission.destroy)
      head :ok
    else
      render nothing: true, status: 403
    end

  end

  def filter_params
    params.permit(:user_id, :user_email)
  end

end

app/controllers/step_permissions_controller.rb
class StepPermissionsController < ApplicationController
  def index
    @step = Step.find(params[:step_id])
    @step_permissions = @step.step_permissions.order('created_at DESC').page(params[:page])
  end

  def create
     @step = Step.find(params[:step_id])
     @step_permission = @step.step_permissions.build(filter_params)

     if @step_permission.save
       render layout: false
     else
       render text: @step_permission.errors.full_messages.first, status: 403
     end
  end

  def destroy
    @step_permission = Step.find(params[:step_id]).step_permissions.find(params[:id])
    if(@step_permission.destroy)
      head :ok
    else
      render nothing: true, status: 403
    end

  end

  def filter_params
    params.permit(:user_id, :user_email)
  end

end

app/views/admin/step_permissions/_search.html.erb
<p>
  <%=form_tag(admin_step_step_permissions_path(step), id: 'step_permission_url', method: :post) do |f| %>
    <div class="input-group">
        <input type='text'
               id='step_permission_user' 
               class='form-control typeahead'
               placeholder='User email'
               data-url='<%= accounts_path(format: :json)%>' />
        <span class="input-group-btn">
          <button class="btn btn-default" id='add-permission' type="button"> Add </button>
        </span>
      </div><!-- /input-group -->
    </div>

    <input type='hidden' id='step_permission_user_value' class='form-control'/>
  <% end %>
</p>

app/views/admin/step_permissions/_step_permission.html.erb
<tr>
  <td><%= step_permission.user_email %></td>
  <td><%= link_to 'Remove', admin_step_step_permission_path(@step, step_permission),
                  class: 'remove-step-permissions',
                  data: { id: step_permission.id } %></td>
</tr>

app/views/admin/step_permissions/create.html.erb
<%= render 'step_permission', step_permission: @step_permission %>

app/views/admin/step_permissions/index.html.erb
<h3> <%= "Step: #{@step.display_name}" %> </h3>

<%= render 'search', step: @step %>

<h3> List of users in this step</h3>

<div class='panel panel-default'>
<table class='table' id='step-permissions-list' >
  <thead>
    <tr>
      <td>Email</td>
      <td width='100'> Action</td>
    </tr>
  </thead>

  <tbody>
    <%= render @step_permissions %>
  </tbody>

</table>
</div>

app/views/admin/step_permissions/new.html.erb
<div class="input-group">
    <input type='text'
           id='step_permission_user' 
           class='form-control typeahead'
           placeholder='User email'
           data-url='<%= accounts_path(format: :json)%>' />
    <span class="input-group-btn">
      <button class="btn btn-default" type="button"> Add </button>
    </span>
  </div><!-- /input-group -->
</div>

<input type='hidden' id='step_permission_user_value' class='form-control'/>