config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'sign_in', to: 'sessions#new'

  resources :sessions, only: [:new, :create]
  delete 'sign_out', to: 'sessions#destroy'

  resources :steps, only: [:index, :edit, :update] do
    put :update_project_variable, on: :member
    get :manifest, on: :member, defaults: { format: :xml }
    post :result, on: :member, defaults: { format: :json }
    put :sync_with_project_variable, on: :member
  end

  resources :period_ratings

  resources :project_variables, only: [:index]

  resources :accounts, only: [:index]

  namespace :admin do
    resources :steps, only: [:index, :edit, :update] do
      resources :step_permissions
    end
  end

end

app/views/layouts/_breadcrumb.html.erb
<ol class="breadcrumb ">
 	<%= render_breadcrumbs :tag => :li, :separator => "" %>
</ol>

app/views/layouts/_config.html.erb
<script>
  window.Config = {
    Flash: {
      key: '<%= flash_config[:key] %>',
      value: "<%= flash_config[:value].html_safe %>"
    }
  }
</script>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
	<% css_class = key == 'notice' ? 'alert-success' : 'alert-danger' %>
  <div class='alert <%= css_class %> alert-dismissible'>
    <button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
    <%= value %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class='copyright'>
  <p>&copy; Copyright 

    <a href='http://www.instedd.org' style='text-decoration:none;'>
      <img src='http://www.ilabsoutheastasia.org/wp-content/themes/instedd_v3/images/favicon.ico' />
      InSTEDD
    </a>
  </p>
</footer>

app/views/layouts/_login_bar.html.erb
<% if current_access.present? %>
  <ul class="nav pull-right">
    <li class="dropdown">
      <% if user_signed_in? %>
        <a data-toggle="dropdown" class="dropdown-toggle blog-nav-item" href="#">
          <%= current_access.email %><b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li>
            <%= link_to 'Sign out', sign_out_path, 
                        method: 'delete', 
                        data: { confirm: 'Are you sure to sign out' } %>
          </li>
        </ul>
      <% end %>
    </li>
  </ul>
<% else %>
  <%= link_to 'Sign in', sign_in_path, class: 'blog-nav-item' %>
<% end %>

app/views/layouts/_menu_bar.html.erb
<% if user_signed_in? %>
	<%= link_to 'Steps', (current_access.admin? ? admin_steps_path : steps_path), class: 'blog-nav-item' %>
	<span>|</span>
<% end %>

app/views/layouts/_nav_bar.html.erb
<div class="blog-masthead">
  <div class='container'>
    <nav class="blog-nav navbar-default">
      <div class='l-side action-menu'>
        <%= link_to ENV['APP_NAME'], root_url, class: 'blog-nav-item' %>
      </div>

      <div class='r-side profile-menu'><%= render 'layouts/login_bar' %></div>
      <% if user_signed_in? %>
      	<div class='r-side'><%= render 'layouts/menu_bar' %></div>
    	<% end %>
    </nav>
  </div>
</div>

app/views/layouts/_notification.html.erb
<div id='notification'>

</div>

<script id='tmpl-notification' type="text/x-tmpl">
  <div class="bs-callout bs-callout-{%=o.type%}">
    <h4>
      <span class='glyphicon glyphicon-{%=o.icon%}'> </span>
      {%=o.title%}
    </h4>
    
    <p>{%=o.body%}</p>
  </div>
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VerboiceExternalStep</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->
    <%= render 'layouts/config' %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  </head>
  <body>

    <%= render 'layouts/nav_bar' %>

    <div class="container app-container">
      <%= render 'layouts/breadcrumb' %>
      <div class="main-content"> <%= yield %> </div>
      <%= render 'layouts/notification' %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/layouts/error.html.erb
<!DOCTYPE html>
<html>
  <head>

    <!--Info -->
    <title><%= "Error :: #{@app_name}" %></title>

    <!--Styling -->
    <style>
      
		html {
			height: 100%;
			background: #fff asset_url("custom_error_pages/bg.png") bottom repeat-x;
		}
		
		body {
			font-family: Helvetica, Arial, Sans-Serif;
			font-size: 14px;
		}
		.error_container {
			display: block;
			margin: auto;
			margin: 10% auto 0 auto;
			width: 30%;
		}
		
		.error_container .error {
			display: block;
			text-align: center;
		}
		
		.error_container .error img.alert {
			display: block;
			margin: 0 auto 25px auto;
		}
		
		.error_container .message > * {
			display: block;
		}
		
		.error_container .message strong {
			font-weight: bold;
			font-size: 1.5em;
			color: #f00;
			margin: 15px 0 0;
		}

		.error_container .message span {
			margin: 5px auto 0;
			font-size: 0.75em;
			color: #606060;
		}
		
		.error_container .contact {
			display: block;
			text-align: center;
			margin: 20px 0 0 0;
		}
		
		.error_container .contact a {
			display: inline-block;
			margin: 0 -1px; /* For inline block & ERB - HAML removes whitespace; ERB does now - http://haml.info/docs/yardoc/file.REFERENCE.html#whitespace_removal__and_ */
			opacity: 0.4;
			transition: opacity 0.15s ease;
		}

		.error_container .contact a img {
			display: block;
			width: 38px;
			height: 38px;
		}
		
		.error_container .contact a:hover {
			opacity: 0.8;
		}

    </style>
  </head>
  
  <!--Body -->
  <body>
    <div class="error_container">
      <%= yield %>
    </div>
  </body>

</html>

app/views/layouts/sign_in.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= ENV['APP_NAME'] %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->
    <%= render 'layouts/config' %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>

    <%= render 'layouts/nav_bar' %>

    <div class="container app-container">
      <div class="main-content"> <%= yield %> </div>
      <%= render 'layouts/notification' %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>